### ISSUE TITLE
在CMU仿真环境中，点击2d nav goal之后模型只出现轨迹，无法控制仿真模型移动

### ISSUE THREAD

**Issue by fishZeng** [Dangko/ego-planner-for-ground-robot#5]
![2023-06-09 21-55-14屏幕截图](https://github.com/Dangko/ego-planner-for-ground-robot/assets/128690427/99ba3a02-163a-49f0-b2d8-da2ff0a635ed)

**Comment by Lec1ercW** [comment]
我也遇到了一样的问题，想请问您如何解决的？

**Comment by Hugo-Xu-maker** [comment]
我也遇到的相同的情况，并且一旦给定目标点其就给定一些报错信息如下所示，请问你们是怎么解决的，可以给一些解决方案吗？太期待了

<img width="2560" height="1600" alt="Image" src="https://github.com/user-attachments/assets/e3eba2ee-76aa-4800-bec6-d1ad0a582322" />
